# Generated by Django 4.2.7 on 2024-02-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk2heal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='psychologist',
            managers=[
            ],
        ),
    ]
