# Generated by Django 4.2.7 on 2024-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2heal', '0002_alter_patient_managers_alter_psychologist_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
