# Generated by Django 4.2.7 on 2024-02-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talk2heal', '0003_remove_patient_date_joined_remove_patient_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='password',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='username',
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='degree',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
