# Generated by Django 4.2.7 on 2024-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2heal', '0004_remove_patient_email_remove_patient_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
