# Generated by Django 4.2.7 on 2024-02-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2heal', '0005_remove_patient_user_remove_psychologist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
