# Generated by Django 4.2.7 on 2024-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2heal', '0006_psychologist_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='myimages/'),
        ),
    ]
