# Generated by Django 4.2.7 on 2024-02-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2heal', '0007_alter_psychologist_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
