# Generated by Django 4.2.7 on 2024-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2heal', '0009_patient_contact_number_alter_patient_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
