# Generated by Django 4.2.7 on 2024-02-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk2heal', '0011_patient_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chat_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
